spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        model: gpt-3.5-turbo

kakao:
  login:
    api_key: ${KAKAO_API_KEY}
    client_secret: ${KAKAO_CLIENT_SECRET}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    uri:
      code: /oauth/authorize
      base: https://kauth.kakao.com

app:
  client:
    url: "http://localhost:5174"

api:
  # 국립해양조사원(Korea Hydrographic and Oceanographic Agency, KHOA)
  khoa:
    base-url: https://apis.data.go.kr/1192136
    service-key: ${DATAPORTAL_KEY}
    type: json
    path:
      fishing: /fcstFishing/GetFcstFishingApiService
      mudflat: /fcstMudflat/GetFcstMudflatApiService
      diving: /fcstSkinScuba/GetFcstSkinScubaApiService
      surfing: /fcstSurfing/GetFcstSurfingApiService

  badanuri:
    key: ${BADANURI_KEY}

  openmeteo:
    base-url: https://api.open-meteo.com/v1/forecast
    timezone: Asia/Seoul

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 300